<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageID>Twine.Twee.FSharp</PackageID>
    <AssemblyName>Twine.Twee.FSharp</AssemblyName>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <!-- NETSDK1138 — 'net6.0' is out of support -->
    <!-- NU1903 — high severity vulnerability -->
    <!-- NU1904 — critical severity vulnerability -->
    <NoWarn>NETSDK1138,NU1903,NU1904</NoWarn>
  </PropertyGroup>
  <ItemGroup>
     <Compile Include="Ast.fs" />
     <Compile Include="Parser/Common.fs" />
     <Compile Include="Parser/PassageName.fs" />
     <Compile Include="Parser/PassageTag.fs" />
     <Compile Include="Parser/PassageTags.fs" />
     <Compile Include="Parser/PassageMetadata.fs" />
     <Compile Include="Parser/PassageHeader.fs" />
     <Compile Include="Parser/PassageBody.fs" />
     <Compile Include="Parser/Passage.fs" />
     <Compile Include="Parser/Document.fs" />
     <Compile Include="Printer/NewlineType.fs" />
     <Compile Include="Printer/PassageName.fs" />
     <Compile Include="Printer/PassageTag.fs" />
     <Compile Include="Printer/PassageTags.fs" />
     <Compile Include="Printer/PassageMetadata.fs" />
     <Compile Include="Printer/PassageHeader.fs" />
     <Compile Include="Printer/PassageBody.fs" />
     <Compile Include="Printer/Passage.fs" />
     <Compile Include="Printer/Document.fs" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
